### ISSUE TITLE
Fix close button for PWA

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/tic-tac-toe#10]
The close button doesn't work on PWA (Mobile App).

**Comment by eemike07** [comment]
I would like to tackle this issue for Hacktoberfest :)  
Please assign.  

Can we review the steps to reproduce this issue and expected behavior?  
I wasn't able to reproduce on my machine.  

I was able to run and deploy w/  
1. `npm run start` 
2. Clicked on Play//Play (Computer) 
3. Clicked on X button at the top-right 
4. Navigates back to home screen.

**Comment by yashchaudhari008** [comment]
You need to install it then test. Also try on mobile when installed.

**Comment by eemike07** [comment]
I have it physically installed on my device.
When I click on "Play" and then hit "X" button, it does return me back to my home screen.

From the home-screen, should the "X" button be disabled // not show?

I'm on an Android Pixel 3a.

**Comment by yashchaudhari008** [comment]
It should ideally close the window.

**Comment by eemike07** [comment]
> It should ideally close the window/app. Else if not possible , you can hide it

Yeah, unfortunately I had to resort to hiding it.  :(  
See pull request for more info.
